site_name: Data_Platform DOC
theme:
  name: readthedocs      

markdown_extensions:
  - admonition  
  - footnotes
  - attr_list
  - md_in_html

nav:
  - Home: index.md
  - API: API.md
  - Nota Fiscal: Leitura_Notas_Fiscais.md

plugins:
    - search
    - mermaid2